# Autogenerated wrapper script for CLAPHost_jll for armv7l-linux-musleabihf
export libclap_host

JLLWrappers.@generate_wrapper_header("CLAPHost")
JLLWrappers.@declare_library_product(libclap_host, "libclap_host.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libclap_host,
        "lib/libclap_host.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
